// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.haikun.jetpackapp.home.ui.demo.datastore.bean;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\"-\n\014MessageEvent\022\014\n\004type\030" +
      "\001 \001(\005\022\017\n\007message\030\002 \001(\tB4\n0com.haikun.ag" +
      "mobile.home.ui.demo.datastore.beanP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MessageEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MessageEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageEvent_descriptor,
        new java.lang.String[] { "Type", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
