// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.haikun.jetpackapp.home.ui.demo.datastore.bean;

public interface MessageEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 type = 1;</code>
   * @return The type.
   */
  int getType();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
